# Generated by Django 5.2 on 2025-04-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setor', to='controle.setor', verbose_name='departamento'),
        ),
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('entrada', models.TimeField(verbose_name='Entrada')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionario', to='controle.funcionario', verbose_name='Nome')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionario', to='controle.setor', verbose_name='departamento')),
            ],
        ),
    ]
