# Generated by Django 5.2 on 2025-04-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_alter_funcionario_setor_controle'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='saida',
            field=models.TimeField(default='11:10', verbose_name='saida'),
            preserve_default=False,
        ),
    ]
