# Generated by Django 5.2 on 2025-04-16 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_controle_saida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome']},
        ),
        migrations.AlterUniqueTogether(
            name='controle',
            unique_together={('nome', 'data')},
        ),
    ]
