# Generated by Django 5.2 on 2025-04-16 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_alter_funcionario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controle',
            options={'ordering': ['nome']},
        ),
    ]
