# Generated by Django 5.2 on 2025-04-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_alter_controle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='saida',
            field=models.TimeField(blank=True, null=True, verbose_name='saida'),
        ),
    ]
