# Generated by Django 5.2 on 2025-04-16 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_alter_controle_entrada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome'], 'verbose_name': 'Cooperado'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': ' Setore'},
        ),
        migrations.AlterField(
            model_name='controle',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionario', to='controle.setor', verbose_name='departamento'),
        ),
    ]
