# Generated by Django 5.2 on 2025-04-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0010_historicalcontrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controle',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='historicalcontrole',
            name='setor',
        ),
    ]
